export const formFields = [
  {
    id: 1,
    name: "nome",
    label: "Nome",
    messageError: "Nome inválido",
    value: "",
  },
  {
    id: 2,
    name: "cnpj",
    label: "CNPJ",
    messageError: "CNPJ inválido",
    value: "",
  },
  {
    id: 3,
    name: "nome_fantasia",
    label: "Nome Fantasia",
    messageError: "Nome Fantasia inválido",
    value: "",
  },
  {
    id: 4,
    name: "email",
    label: "E-mail",
    messageError: "E-mail inválido",
    value: "",
  },
  {
    id: 5,
    name: "contato",
    label: "Contato",
    messageError: "Contato inválido",
    value: "",
  },
  {
    id: 6,
    name: "cpf",
    label: "CPF",
    messageError: "CPF inválido",
    value: "",
  },
  {
    id: 7,
    name: "rua",
    label: "Rua",
    messageError: "Rua inválida",
    value: "",
  },
  {
    id: 8,
    name: "numero",
    label: "Número",
    messageError: "Número inválido",
    value: "",
  },
  {
    id: 9,
    name: "bairro",
    label: "Bairro",
    messageError: "Bairro inválido",
    value: "",
  },
  {
    id: 10,
    name: "cidade",
    label: "Cidade",
    messageError: "Cidade inválida",
    value: "",
  },
  {
    id: 11,
    name: "cep",
    label: "CEP",
    messageError: "CEP inválido",
    value: "",
  },
  {
    id: 12,
    name: "uf",
    label: "UF",
    messageError: "UF inválido",
    value: "",
  },
  {
    id: 13,
    name: "senha",
    label: "Senha",
    messageError: "Senha inválida",
    value: "",
    type: "password",
  }
];
